name: Deploy anaedani

on:
  push:
    branches: [main]

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy no pipelines
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TRIGGER }}
          repository: paulosix12/pipelines
          event-type: deploy
          client-payload: '{"site_name": "anaedani", "repo_name": "Site-de-Casamento-Ana-e-Dani"}'
